# Basic `dependabot.yml` file with
# minimum configuration for two package managers
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/helyos_dashboard"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "23:00"
    groups:
      all-deps:
        patterns:
          - "*"
        commit-message:
          prefix: "deps:helyos_dashboard"
          include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    labels:
      - "npm"
      - "dependencies"
      - "helyos_dashboard"

  - package-ecosystem: "npm"
    directory: "/helyos_server"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "23:00"
    groups:
      all-deps:
        patterns:
          - "*"
        commit-message:
          prefix: "deps:helyos_server"
          include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    labels:
      - "npm"
      - "dependencies"
      - "helyos_server"

  - package-ecosystem: "npm"
    directory: "/tests"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "23:00"
    groups:
      all-deps:
        patterns:
          - "*"
        commit-message:
          prefix: "deps:tests"
          include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    labels:
      - "npm"
      - "dependencies"
      - "tests"