version: '2.0'

missions:

    driving:
      maxagents: 1
      description: "drive from a to b"
      settings: >
            {"interface": "webbrowser",
              "auth" :"required"}
      
      recipe:
        steps:
          - step: "A"
            service_type: "drive"
            request_order: 1
            apply_result: true
            override_config: "{}"


    mapping:
      maxagents: 0
      description: "cover area a x b"
      settings: >
            {"interface": "webbrowser",
              "auth" :"required"}
      
      recipe:
        steps:
          - step: "A"
            service_type: "map"
            request_order: 1
            apply_result: true
            override_config: "{}"
          
