# Basic `dependabot.yml` file with
# minimum configuration for two package managers
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directories:
        - "/helyos_dashboard"
        - "/helyos_server"
        - "/tests"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "23:00"
    commit-message:
      prefix: "deps"  # Custom prefix for the PR titles