name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        cd packaging
        docker build --platform=linux/amd64  -f ./Dockerfile -t helyosframework/helyos_core:test ..

    - name: Install dependencies
      run: |
        cd tests
        npm install

    - name: Run tests
      run: |
        cd tests
        npm run test